import Link from "next/link";
import { ArrowLeft, ChevronDown, Search, Sparkles } from "lucide-react";
import { saveUserSubscriptionAction } from "@/app/admin/actions";
import { StatusBadge } from "@/components/admin/shared/status-badge";
import { AdminPagination } from "@/components/admin/tables/admin-pagination";
import { getAdminSubscriptionEditorOptions, listAdminUserSubscriptions } from "@/lib/supabase/admin/subscriptions";
import { formatAdminDateTime } from "@/lib/supabase/admin/shared";

type Props = { searchParams: Promise<{ q?: string; status?: "active" | "cancelled" | "expired" | "past_due"; planId?: string; userId?: string; page?: string }> };
const statuses = [{ value: "active", label: "Actif" }, { value: "cancelled", label: "Annulé" }, { value: "expired", label: "Expiré" }, { value: "past_due", label: "Paiement en retard" }];

export default async function Page({ searchParams }: Props) {
  const params = await searchParams;
  const [data, options] = await Promise.all([listAdminUserSubscriptions({ page: params.page ? Number(params.page) : 1, search: params.q, status: params.status ?? "", planId: params.planId ?? "", userId: params.userId ?? "" }), getAdminSubscriptionEditorOptions()]);
  return <div className="space-y-5 pb-10">
    <header className="flex flex-col gap-5 rounded-[28px] bg-[#173d2c] p-6 text-white sm:flex-row sm:items-end sm:justify-between sm:p-8"><div><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-white/65"><ArrowLeft className="h-4 w-4" />Vue d’ensemble</Link><p className="mt-7 text-xs font-bold uppercase tracking-[.2em] text-[#f2c66f]">Holistique Premium</p><h1 className="mt-3 font-serif text-3xl sm:text-4xl">Abonnés</h1><p className="mt-2 text-sm text-white/65">Gérez les formules et les dates d’accès des lecteurs.</p></div><span className="rounded-full border border-white/20 px-4 py-2 text-sm font-bold">{data.pagination.total} abonnement{data.pagination.total > 1 ? "s" : ""}</span></header>

    <details className="group rounded-[24px] border border-[#ded3c2] bg-[#fffaf2] p-4"><summary className="flex cursor-pointer list-none items-center justify-between font-bold text-[#17231d] [&::-webkit-details-marker]:hidden"><span className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#b85135]" />Créer un abonnement</span><ChevronDown className="h-4 w-4 transition group-open:rotate-180" /></summary><form action={saveUserSubscriptionAction} className="mt-5 grid gap-3 border-t border-[#e3d8c8] pt-5 md:grid-cols-2 xl:grid-cols-5"><input type="hidden" name="redirect_to" value="/admin/subscriptions/users" /><select name="user_id" className="h-11 rounded-xl border border-[#d9cebd] bg-white px-3 text-sm">{options.users.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select name="plan_id" className="h-11 rounded-xl border border-[#d9cebd] bg-white px-3 text-sm">{options.plans.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select name="status" defaultValue="active" className="h-11 rounded-xl border border-[#d9cebd] bg-white px-3 text-sm">{statuses.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><input type="datetime-local" name="started_at" aria-label="Date de début" className="h-11 rounded-xl border border-[#d9cebd] bg-white px-3 text-sm" /><button className="h-11 rounded-full bg-[#173d2c] px-5 text-sm font-bold text-white">Créer</button></form></details>

    <form action="/admin/subscriptions/users" className="grid gap-3 rounded-[24px] border border-[#ded3c2] bg-white p-4 lg:grid-cols-[1fr_200px_220px_auto]"><label className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#887f74]" /><input name="q" defaultValue={params.q} placeholder="Lecteur ou formule" className="h-11 w-full rounded-full border border-[#d9cebd] bg-[#fffaf2] pl-10 pr-4" /></label><select name="status" defaultValue={params.status ?? ""} className="h-11 rounded-xl border border-[#d9cebd] bg-white px-3 text-sm"><option value="">Tous les statuts</option>{statuses.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select name="planId" defaultValue={params.planId ?? ""} className="h-11 rounded-xl border border-[#d9cebd] bg-white px-3 text-sm"><option value="">Toutes les formules</option>{options.plans.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><button className="h-11 rounded-full bg-[#173d2c] px-5 text-sm font-bold text-white">Filtrer</button></form>

    <section className="overflow-hidden rounded-[28px] border border-[#ded3c2] bg-white px-5 sm:px-6">{data.items.map((item) => <article key={item.id} className="border-b border-[#e8dfd2] py-5 last:border-0"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><StatusBadge kind="subscription" value={item.status} /><h2 className="mt-3 truncate font-serif text-xl text-[#17231d]">{item.user_name}</h2><p className="mt-1 text-sm font-semibold text-[#a94b34]">{item.plan_name}</p><p className="mt-2 text-xs text-[#92887c]">Du {formatAdminDateTime(item.started_at)} au {formatAdminDateTime(item.expires_at)}</p></div><form action={saveUserSubscriptionAction} className="flex flex-wrap gap-2"><input type="hidden" name="subscription_id" value={item.id} /><input type="hidden" name="user_id" value={item.user_id} /><input type="hidden" name="plan_id" value={item.plan_id} /><input type="hidden" name="started_at" value={item.started_at} /><input type="hidden" name="redirect_to" value="/admin/subscriptions/users" /><select name="status" defaultValue={item.status} className="h-10 rounded-xl border border-[#d9cebd] bg-white px-3 text-sm">{statuses.map((status) => <option key={status.value} value={status.value}>{status.label}</option>)}</select><input type="datetime-local" name="expires_at" defaultValue={item.expires_at?.slice(0, 16) ?? ""} aria-label="Expiration" className="h-10 rounded-xl border border-[#d9cebd] px-3 text-sm" /><button className="h-10 rounded-full bg-[#173d2c] px-4 text-sm font-bold text-white">Enregistrer</button></form></div></article>)}</section>
    <AdminPagination basePath="/admin/subscriptions/users" pagination={data.pagination} params={{ q: params.q ?? "", status: params.status ?? "", planId: params.planId ?? "", userId: params.userId ?? "" }} />
  </div>;
}
