import Link from "next/link";
import { ArrowLeft, Highlighter, Search } from "lucide-react";
import { deleteHighlightAction } from "@/app/admin/actions";
import { ConfirmSubmitButton } from "@/components/admin/forms/confirm-submit-button";
import { AdminNotice } from "@/components/admin/shared/admin-notice";
import { AdminPagination } from "@/components/admin/tables/admin-pagination";
import { listAdminHighlights } from "@/lib/supabase/admin/highlights";
import { formatAdminDateTime } from "@/lib/supabase/admin/shared";

type Props = { searchParams: Promise<{ q?: string; color?: string; page?: string }> };
const colors: Record<string, { label: string; style: string }> = { yellow: { label: "Jaune", style: "bg-amber-100 text-amber-800" }, blue: { label: "Bleu", style: "bg-sky-100 text-sky-800" }, green: { label: "Vert", style: "bg-emerald-100 text-emerald-800" }, pink: { label: "Rose", style: "bg-rose-100 text-rose-800" } };

export default async function Page({ searchParams }: Props) {
  const params = await searchParams;
  const data = await listAdminHighlights({ page: params.page ? Number(params.page) : 1, search: params.q, color: params.color ?? "" });
  return <div className="space-y-5 pb-10">
    <header className="flex flex-col gap-5 rounded-[28px] bg-[#173d2c] p-6 text-white sm:flex-row sm:items-end sm:justify-between sm:p-8"><div><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-white/65"><ArrowLeft className="h-4 w-4" />Vue d’ensemble</Link><p className="mt-7 text-xs font-bold uppercase tracking-[.2em] text-[#f2c66f]">Activité de lecture</p><h1 className="mt-3 font-serif text-3xl sm:text-4xl">Annotations</h1><p className="mt-2 text-sm text-white/65">Consultez les passages enregistrés par les lecteurs et intervenez seulement si nécessaire.</p></div><span className="rounded-full border border-white/20 px-4 py-2 text-sm font-bold">{data.pagination.total} annotation{data.pagination.total > 1 ? "s" : ""}</span></header>
    {data.notices.length ? <div className="grid gap-3 md:grid-cols-2">{data.notices.map((notice) => <AdminNotice key={notice.id} tone={notice.tone} title={notice.title} description={notice.description} />)}</div> : null}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.stats.byColor.map((item) => <article key={item.label} className="rounded-2xl border border-[#ded3c2] bg-white p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${colors[item.label]?.style ?? "bg-[#f1ece4]"}`}>{colors[item.label]?.label ?? item.label}</span><p className="mt-4 text-2xl font-bold text-[#17231d]">{item.value}</p><p className="text-xs text-[#766e64]">annotations</p></article>)}</div>
    <form action="/admin/highlights" className="grid gap-3 rounded-[24px] border border-[#ded3c2] bg-white p-4 lg:grid-cols-[1fr_200px_auto]"><label className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#887f74]" /><input name="q" defaultValue={params.q} placeholder="Lecteur ou livre" className="h-11 w-full rounded-full border border-[#d9cebd] bg-[#fffaf2] pl-10 pr-4" /></label><select name="color" defaultValue={params.color ?? ""} className="h-11 rounded-xl border border-[#d9cebd] bg-white px-3 text-sm"><option value="">Toutes les couleurs</option>{Object.entries(colors).map(([value, item]) => <option key={value} value={value}>{item.label}</option>)}</select><button className="h-11 rounded-full bg-[#173d2c] px-5 text-sm font-bold text-white">Filtrer</button></form>
    <section className="grid gap-4 md:grid-cols-2">{data.items.map((entry) => <article key={entry.id} className="rounded-[24px] border border-[#ded3c2] bg-white p-5"><div className="flex items-center justify-between gap-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${colors[entry.color]?.style ?? "bg-[#f1ece4]"}`}>{colors[entry.color]?.label ?? entry.color}</span><span className="text-xs text-[#92887c]">Page {entry.page}</span></div><blockquote className="mt-5 border-l-2 border-[#e8ac42] pl-4 font-serif text-lg leading-7 text-[#403a34]">{entry.text?.slice(0, 220) || entry.note || "Annotation sans texte"}</blockquote>{entry.note && entry.text ? <p className="mt-4 rounded-xl bg-[#fffaf2] p-3 text-sm text-[#766e64]">{entry.note}</p> : null}<div className="mt-5 flex items-end justify-between gap-3 border-t border-[#e8dfd2] pt-4"><div className="min-w-0"><p className="truncate text-sm font-bold text-[#17231d]">{entry.book_title}</p><p className="mt-1 truncate text-xs text-[#837a70]">{entry.user_name} · {formatAdminDateTime(entry.created_at)}</p></div><form action={deleteHighlightAction}><input type="hidden" name="highlight_id" value={entry.id} /><input type="hidden" name="redirect_to" value="/admin/highlights" /><ConfirmSubmitButton label="Supprimer" confirmMessage="Supprimer cette annotation ?" className="text-xs font-bold text-red-700" /></form></div></article>)}{!data.items.length ? <div className="col-span-full rounded-[28px] border border-[#ded3c2] bg-white py-20 text-center"><Highlighter className="mx-auto h-8 w-8 text-[#b7aa9a]" /><h2 className="mt-4 font-serif text-2xl">Aucune annotation trouvée</h2></div> : null}</section>
    <AdminPagination basePath="/admin/highlights" pagination={data.pagination} params={{ q: params.q ?? "", color: params.color ?? "" }} />
  </div>;
}
